version: '3'
volumes:
{%- if cookiecutter.database == "PostgreSQL" %}
  local_postgres_data: {}
  local_postgres_data_backups: {}
{%- elif cookiecutter.database == "MySQL" %}
  local_mysql_data: {}
  local_mysql_data_backups: {}
{% endif %}

services:
  db:
{%- if cookiecutter.database == "PostgreSQL" %}
    image: 'postgres:12.2'
    volumes:
      - 'local_postgres_data:/var/lib/postgresql/data'
      - 'local_postgres_data_backups:/backups'
{%- elif cookiecutter.database == "MySQL" %}
    image: 'mysql:5.7'
    volumes:
      - 'local_mysql_data:/var/lib/mysql'
      - 'local_mysql_data_backups:/backups'
{% endif %}
    env_file:
      - local/environment
  django:
    build:
      context: .
      args:
        DEVEL: 'yes'
    image: '{{ cookiecutter.project_slug }}_local_django:dev'
    command: 'python manage.py runserver_plus 0.0.0.0:8000'
    volumes:
      - '.:/app/src:z'
    env_file:
      - local/environment
    depends_on:
      - migrate
      - mailhog
    links:
      - db
      - mailhog
  migrate:
    build:
      context: .
      args:
        DEVEL: 'yes'
    image: '{{ cookiecutter.project_slug }}_local_django:dev'
    command: python manage.py migrate
    volumes:
      - '.:/app/src:z'
    env_file:
      - local/environment
    depends_on:
      - db
    links:
      - db
  mailhog:
    image: 'mailhog/mailhog:v1.0.0'
  redis:
    image: 'redis:latest'
