apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{cookiecutter.project_dash}}

bases:
 - ../base

patches:
- path: patches.yaml
- patch: |
    $patch: delete
    kind: Service
    metadata:
      name: mailhog
  target:
    kind: Service
    name: mailhog
- patch: |
    $patch: delete
    kind: Deployment
    metadata:
      name: mailhog
  target:
    kind: Deployment
    name: mailhog

configMapGenerator:
  - name: django-config
    behavior: merge
    literals:
     - ENVIRONMENT="production"
