apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{ cookiecutter.project_dash }}-prod

resources:
  - ../base
  - certificate.yaml
  - cluster-issuer.yaml
  - ingress-route.yaml
  - postgres.cnpg.yaml
  - secrets.yaml

patches:
  - path: patch-django.yaml
  - path: patch-react.yaml

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
     - ENVIRONMENT="production"

images:
  - name: backend
    newName: {{ cookiecutter.aws_account_id }}.dkr.ecr.{{ cookiecutter.aws_region }}.amazonaws.com/{{ cookiecutter.project_dash }}-backend
    newTag: latest
  - name: frontend
    newName: {{ cookiecutter.aws_account_id }}.dkr.ecr.{{ cookiecutter.aws_region }}.amazonaws.com/{{ cookiecutter.project_dash }}-frontend
    newTag: latest
