$patch: delete
apiVersion: v1
kind: Service
metadata:
  labels:
    tier: smtp
  name: mailhog
---
$patch: delete
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tier: smtp
  name: mailhog