apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-sandbox-cert
spec:
  secretName: cluster-sandbox-cert-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "k8s.sandbox.{{ cookiecutter.domain_name }}"
  - "api.sandbox.{{ cookiecutter.domain_name }}"
