apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{ cookiecutter.project_dash }}-sandbox

bases:
 - ../base

patches:
 - path: patches.yaml

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
     - ENVIRONMENT="sandbox"
