apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{ cookiecutter.project_dash }}-sandbox

resources:
  - ../prod
  - ../mailhog
  - secrets.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/dnsNames
      value:
        - api.sandbox.{{ cookiecutter.domain_name }}
        - k8s.sandbox.{{ cookiecutter.domain_name }}
  target:
    kind: Certificate
    name: cluster-cert

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
     - ENVIRONMENT="sandbox"

images:
  - name: {{ cookiecutter.project_slug }}_local_django
    newName: {{ cookiecutter.aws_account_id }}.dkr.ecr.{{ cookiecutter.aws_region }}.amazonaws.com/{{ cookiecutter.project_dash }}-backend
    newTag: latest
  - name: {{ cookiecutter.project_slug }}_local_frontend
    newName: {{ cookiecutter.aws_account_id }}.dkr.ecr.{{ cookiecutter.aws_region }}.amazonaws.com/{{ cookiecutter.project_dash }}-frontend
    newTag: latest
