name: Create scaf project

on: [push, pull_request]

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Install Requirements
      shell: bash
      run: |
        curl -sSL https://raw.githubusercontent.com/sixfeetup/scaf/$GITHUB_REF_NAME/install.sh | sh

    - name: Create Project with Scaf
      shell: bash
      run: |
        /usr/local/bin/scaf myproject

