name: Create scaf project

on: [push, pull_request]

jobs:
  build-and-push:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: sixfeetup/scaf:${{ github.sha }}

  setup:
    environment: dev
    needs: build-and-push
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Install Requirements
      shell: bash
      run: |
        curl -sSL https://raw.githubusercontent.com/sixfeetup/scaf/$GITHUB_REF_NAME/install.sh | sh

    - name: Create Project with Scaf
      shell: bash
      run: |
        IMAGE_TAG=$GITHUB_SHA
        /usr/local/bin/scaf myproject --no-input

